id: P662822D8
initial_creation_type: input
source_metadata:
  title: TENGYUR (Tibetan Letters)
  volumes:
    323adc9550ed4e3886c3e4f811609cc9:
      title: ༠༠༡  ཀ།
      base_file: ༠༠༡  ཀ།.txt
      work_id: W9C3B4D61
    6349199fd76d406d886f74f52b47504d:
      title: ༠༠༢  ཀ།
      base_file: ༠༠༢  ཀ།.txt
      work_id: W3CB61478
    b934ebcb00024e7f9653e502e9a2526e:
      title: ༠༠༣  ཁ།
      base_file: ༠༠༣  ཁ།.txt
      work_id: W6596FA85
    ca830515c54b4a318474e3391be86b80:
      title: ༠༠༤  ག
      base_file: ༠༠༤  ག.txt
      work_id: WAD8D013A
    cf2f00113f05482285c270eaa0b96daf:
      title: ༠༠༥  ང་།
      base_file: ༠༠༥  ང་།.txt
      work_id: W41A4CEC9
    85cc0ee697d44950a3426a45774c798c:
      title: ༠༠༦  ཅ།
      base_file: ༠༠༦  ཅ།.txt
      work_id: W11A42FA4
    dfdfd1b869c34c58bd5a7eaf6fb4fe01:
      title: ༠༠༧  ཆ།
      base_file: ༠༠༧  ཆ།.txt
      work_id: WB0E9BCF9
    ea062ae4716d46998b065e325f4417d3:
      title: ༠༠༨  ཇ།
      base_file: ༠༠༨  ཇ།.txt
      work_id: W68549FCC
    b76ea568b1704cdc8a102b44b3122a27:
      title: ༠༠༩  ཉ།
      base_file: ༠༠༩  ཉ།.txt
      work_id: W11482F6C
    46b51f6cafa64f47bd334cb2e121c092:
      title: ༠༡༠  ཏ།
      base_file: ༠༡༠  ཏ།.txt
      work_id: WE0C9990C
    c6b5e82c378d487fa3ce46e9fc8a4d5d:
      title: ༠༡༡  ཐ།
      base_file: ༠༡༡  ཐ།.txt
      work_id: WC21D4D92
    23d30d7b5511413e8f561d4361f9fd5c:
      title: ༠༡༣  ན།
      base_file: ༠༡༣  ན།.txt
      work_id: W4BCCB33C
    b6c2bd0e14b04efa81b6eb7095c83d95:
      title: ༠༡༤  པ།
      base_file: ༠༡༤  པ།.txt
      work_id: W9A62A894
    ae68b83c58ed4feba4ac798152f87996:
      title: ༠༡༥  ཕ།
      base_file: ༠༡༥  ཕ།.txt
      work_id: W934C5DA7
    de183b21c3914d1a909aab553d25d942:
      title: ༠༡༦  བ།
      base_file: ༠༡༦  བ།.txt
      work_id: W974358A9
    0bca27cb9ec94b71a6f475cfd0b6aadd:
      title: ༠༡༧  མ།
      base_file: ༠༡༧  མ།.txt
      work_id: W78784888
    dd8e4b56faf441219082e0f41bd96eb3:
      title: ༠༡༨  ཙ།
      base_file: ༠༡༨  ཙ།.txt
      work_id: WFFE7CFF6
    8ed6a6e569ce4b58ba7332e92d40732d:
      title: ༠༡༩  ཚ།
      base_file: ༠༡༩  ཚ།.txt
      work_id: W5A4A8A93
    f5034ee9f5744ac499ff4130dc3a009e:
      title: ༠༢༠  ཛ།
      base_file: ༠༢༠  ཛ།.txt
      work_id: W45620F0F
    ee8e830850874c5484c2095e0bffe14e:
      title: ༠༢༡  ཝ།
      base_file: ༠༢༡  ཝ།.txt
      work_id: WCFCF7AC7
    0616cfd0a8b24ace886380dd87691c2a:
      title: ༠༢༢  ཞ།
      base_file: ༠༢༢  ཞ།.txt
      work_id: WFF3EE634
    24cc1664b34941f59f1b04ca85174acc:
      title: ༠༢༣  ཟ།
      base_file: ༠༢༣  ཟ།.txt
      work_id: W24B8C217
    945631857f5448149f7da8424e51c61b:
      title: ༠༢༤  འ།
      base_file: ༠༢༤  འ།.txt
      work_id: WBE2B8138
    85a5ead3fd4a402f96c487fecb4eee70:
      title: ༠༢༥  ཡ།
      base_file: ༠༢༥  ཡ།.txt
      work_id: W5FAFCDF9
    c88f93b2703d430ea18949112c9d00b9:
      title: ༠༢༦  ར།
      base_file: ༠༢༦  ར།.txt
      work_id: WC9CA3B78
    3962871911cc4ccbb80943c04b9e25c3:
      title: ༠༢༧  ལ།
      base_file: ༠༢༧  ལ།.txt
      work_id: W18DB4CA4
    6f583e4cdd1243b09eb99bcbeaea5a1a:
      title: ༠༢༨  ཤ།
      base_file: ༠༢༨  ཤ།.txt
      work_id: W27582219
    976cfa46f4cd4e75bed503cd7398b730:
      title: ༠༣༠  ཧ།
      base_file: ༠༣༠  ཧ།.txt
      work_id: WF7D3BF49
    49eedb1a1ace41d09b439296f7c50045:
      title: ༠༣༡  ཨ།
      base_file: ༠༣༡  ཨ།.txt
      work_id: WB6EF0B7A
    2bdcc9588c53434daa30b7e839ff6409:
      title: ༠༣༣  ཁི།
      base_file: ༠༣༣  ཁི།.txt
      work_id: W84A37B66
    1cb5c6b19fe345278a487a88be8489f5:
      title: ༠༣༤  གི
      base_file: ༠༣༤  གི.txt
      work_id: WABD1C1D4
    f26b91de99b940cfa7270ae85cdaa9e8:
      title: ༠༣༥  ངི་།
      base_file: ༠༣༥  ངི་།.txt
      work_id: W1450A441
    0fe1cbca98ae47deaf23fb8e60769bb3:
      title: ༠༣༦  ཅི།
      base_file: ༠༣༦  ཅི།.txt
      work_id: W8F45251C
    a2381a48bae1406791ca050f61544194:
      title: ༠༣༧  ཆི།
      base_file: ༠༣༧  ཆི།.txt
      work_id: WF40BB67E
    19c90c861166413fa847c75f431093fd:
      title: ༠༣༨  ཇི།
      base_file: ༠༣༨  ཇི།.txt
      work_id: WEDC5BFAF
    0597ba79e1644b98baf5b7afc3e581a4:
      title: ༠༣༩  ཉི།
      base_file: ༠༣༩  ཉི།.txt
      work_id: W1BBC27C6
    c9b78d8652b04b67b2104310b8a5794b:
      title: ༠༤༠  ཏི།
      base_file: ༠༤༠  ཏི།.txt
      work_id: W9C79D433
    f744c13e11504e59be75d58c1771ea9b:
      title: ༠༤༡  ཐི།
      base_file: ༠༤༡  ཐི།.txt
      work_id: WB709490A
    09b0dc316bc3487cb16ffa873da61419:
      title: ༠༤༢  དི།
      base_file: ༠༤༢  དི།.txt
      work_id: W01237FF1
    2bdb75face6c4467a4fdfde0fc394b92:
      title: ༠༤༣  ནི།
      base_file: ༠༤༣  ནི།.txt
      work_id: W47E4F7A7
    03cfa87829434051a8c08faacf7f9a55:
      title: ༠༤༤  པི།
      base_file: ༠༤༤  པི།.txt
      work_id: W633CFBB0
    19bfcb600a74411f94857955e325ccec:
      title: ༠༤༥  ཕི།
      base_file: ༠༤༥  ཕི།.txt
      work_id: WF474011C
    1b7e3824b7354a73a1de3921f4b3f85a:
      title: ༠༤༦  བི།
      base_file: ༠༤༦  བི།.txt
      work_id: W28408544
    6a539b38f678404e83aa5028da58918e:
      title: ༠༤༧  མི།
      base_file: ༠༤༧  མི།.txt
      work_id: WF9CD5D94
    1861e63774034affae7435c33ee96bf5:
      title: ༠༤༨  ཙི།
      base_file: ༠༤༨  ཙི།.txt
      work_id: WBBC5615F
    41f2daf8ac744b15bc29faaaedb95847:
      title: ༠༤༩  ཚི།
      base_file: ༠༤༩  ཚི།.txt
      work_id: WACDDD3D2
    6f7d05577b804b9fa92291ee84833f80:
      title: ༠༥༠  ཛི།
      base_file: ༠༥༠  ཛི།.txt
      work_id: WE709877E
    85cabfeab6e649469ba2dee9a2f6366c:
      title: ༠༥༡  ཝི།
      base_file: ༠༥༡  ཝི།.txt
      work_id: W74499F2E
    200ddd4422224b54a43891699c746502:
      title: ༠༥༢  ཞི།
      base_file: ༠༥༢  ཞི།.txt
      work_id: WB413837C
    4e9e7e07804e410b9a249b33e46ff05e:
      title: ༠༥༣  ཟི།
      base_file: ༠༥༣  ཟི།.txt
      work_id: W7F27C784
    a3a0af0e500b4358a6332c9196a326e5:
      title: ༠༥༤  འི།
      base_file: ༠༥༤  འི།.txt
      work_id: WD4BDBD76
    ac8b817ef427428e80316e67eaba0d63:
      title: ༠༥༦  རི།
      base_file: ༠༥༦  རི།.txt
      work_id: W0A263288
    c9b19ac7e60343e68fe8a75b0a1b76de:
      title: ༠༥༩  སི།
      base_file: ༠༥༩  སི།.txt
      work_id: WB45877BF
    61d0947461b5429381ca4875dc85dc7a:
      title: ༠༦༡  ཨི།
      base_file: ༠༦༡  ཨི།.txt
      work_id: WFD7F62A1
    c3eb87bdb6434385ae322e2df08f55c5:
      title: ༠༦༢  ཀུ།
      base_file: ༠༦༢  ཀུ།.txt
      work_id: W4FE3C342
    3bbf1af6a9a1452f90f1450dd95fbaba:
      title: ༠༦༣  ཁུ།
      base_file: ༠༦༣  ཁུ།.txt
      work_id: W64AE4B7E
    ee18c37a559a4fba8fe2a7c0f4481535:
      title: ༠༦༤  གུ
      base_file: ༠༦༤  གུ.txt
      work_id: WAAF42161
    58037e65c9ef477687ffe06fd982f501:
      title: ༠༦༥  ངུ་།
      base_file: ༠༦༥  ངུ་།.txt
      work_id: W5AFEE039
    d5be009ade0b41b491522f1ab7358718:
      title: ༠༦༦  ཅུ།
      base_file: ༠༦༦  ཅུ།.txt
      work_id: W51745ADA
    4934b0c2b23b4c67a9ae274e951fd0a5:
      title: ༠༦༧  ཆུ།
      base_file: ༠༦༧  ཆུ།.txt
      work_id: W750A0ABA
    ff67e5cca9e24ffca09bca4b366152d0:
      title: ༠༦༨  ཇུ།
      base_file: ༠༦༨  ཇུ།.txt
      work_id: WEAA597CE
    bbd9c4280a254f65aa28fe5ea6444c9c:
      title: ༠༦༩  ཉུ།
      base_file: ༠༦༩  ཉུ།.txt
      work_id: W1B8DABD7
    ee43448253b44adb9a2203f11634c72f:
      title: ༠༧༠  ཏུ།
      base_file: ༠༧༠  ཏུ།.txt
      work_id: W4B51145E
    9f578031fe2f4304be3e6693734583d0:
      title: ༠༧༡  ཐུ།
      base_file: ༠༧༡  ཐུ།.txt
      work_id: WA5A74657
    e7a838ca7ca144e2b03339125d1c2eb9:
      title: ༠༧༢  དུ།
      base_file: ༠༧༢  དུ།.txt
      work_id: W771974C0
    04d3898bb0d545418c157de361484480:
      title: ༠༧༣  ནུ།
      base_file: ༠༧༣  ནུ།.txt
      work_id: WBBD0A0DF
    dd5780f7f902476a808ae6673366d57f:
      title: ༠༧༤  པུ།
      base_file: ༠༧༤  པུ།.txt
      work_id: WD4B45B44
    cce18591602440b7968ce7a25a39aa8d:
      title: ༠༧༥  ཕུ།
      base_file: ༠༧༥  ཕུ།.txt
      work_id: W92E08445
    a3d3bd6c3c404e47a4a45227570a16a8:
      title: ༠༧༦  བུ།
      base_file: ༠༧༦  བུ།.txt
      work_id: WA2C20B14
    58bd52707c704a068feab847b09ba87b:
      title: ༠༧༧  མུ།
      base_file: ༠༧༧  མུ།.txt
      work_id: WCE111DEE
    87c9c9ec17824708a4423fe894b5af94:
      title: ༠༧༨  ཙུ།
      base_file: ༠༧༨  ཙུ།.txt
      work_id: WF115178E
    854d75c8a414496eac93b68247b204ca:
      title: ༠༧༩  ཚུ།
      base_file: ༠༧༩  ཚུ།.txt
      work_id: W84814B8E
    03abf11b03e447c7bf535fa5e91a51d4:
      title: ༠༨༠  ཀ།
      base_file: ༠༨༠  ཀ།.txt
      work_id: W7BFF877E
    4b40a92a76d649998e5ea39a8d4f37c7:
      title: ༠༨༡  ཁ།
      base_file: ༠༨༡  ཁ།.txt
      work_id: W2EC79AAA
    93f671cf163744f5844d9db08b88db42:
      title: ༠༨༥  ཆ།
      base_file: ༠༨༥  ཆ།.txt
      work_id: W6F44C2F1
    c65e2dcdf35d48b9a174276e83072bd5:
      title: ༠༨༦  ཇ།
      base_file: ༠༨༦  ཇ།.txt
      work_id: WD3252A47
    aa62a56ede764324ac4852e4b385362e:
      title: ༠༨༧  ཉ།
      base_file: ༠༨༧  ཉ།.txt
      work_id: WED497436
    47750520ca6b43d8b5714112f32583f9:
      title: ༠༨༨  ཏ།
      base_file: ༠༨༨  ཏ།.txt
      work_id: W64084518
    fa36044c26a448f38e771ca3e109d5a4:
      title: ༠༨༩  ཐ།
      base_file: ༠༨༩  ཐ།.txt
      work_id: W24D21A49
    7922aa677dfc40c7bc34844f28694f0f:
      title: ༠༩༠  ད།
      base_file: ༠༩༠  ད།.txt
      work_id: W5D0C0CFE
    e0629f9165464375b7da4b7bf4f00911:
      title: ༠༩༣  ཕ།
      base_file: ༠༩༣  ཕ།.txt
      work_id: W9850309A
    0b77cad3999e42d29b580574bac085fb:
      title: ༠༩༤  བ།
      base_file: ༠༩༤  བ།.txt
      work_id: W6C059F2F
    3a417e525b6040168167391e94f191db:
      title: ༠༩༥  མ།
      base_file: ༠༩༥  མ།.txt
      work_id: W9DF45443
    522727935529454e997863819cad31d9:
      title: ༠༩༦  ཙ།
      base_file: ༠༩༦  ཙ།.txt
      work_id: W1301E2E2
    0ed9154a26834fa784c9156b370dbb19:
      title: ༠༩༧  ཚ།
      base_file: ༠༩༧  ཚ།.txt
      work_id: W091D20AD
    dc3d2e166b604b12b17d4409102e6d27:
      title: ༠༩༨  ཛ།
      base_file: ༠༩༨  ཛ།.txt
      work_id: W8D85458B
    c0c5943224ef4e558bf1068d0f7241dc:
      title: ༡༠༢  འ།
      base_file: ༡༠༢  འ།.txt
      work_id: WC40F41DF
    7271fe1853d84d22b77fa7047bb56a99:
      title: ༡༠༣  ཡ།
      base_file: ༡༠༣  ཡ།.txt
      work_id: W418C90D9
    cda473e8f43447b38db6f1dabbb88a11:
      title: ༡༠༤  ར།
      base_file: ༡༠༤  ར།.txt
      work_id: W0BB05143
    9bf6f2c1fec94ebc915203415ca9de38:
      title: ༡༠༥  ལ།
      base_file: ༡༠༥  ལ།.txt
      work_id: W59EE7750
    0c7a41da129a49ae8c8293dc75d6ab08:
      title: ༡༠༦  ཤ།
      base_file: ༡༠༦  ཤ།.txt
      work_id: WC255CB6B
    9f7b2f3de6524ba1ae4344cbf95d59f7:
      title: ༡༠༧  ས།
      base_file: ༡༠༧  ས།.txt
      work_id: W1C4CFCCB
    90cfced4a9cd42e5adc7fafdff7a7377:
      title: ༡༠༨  ཧ།
      base_file: ༡༠༨  ཧ།.txt
      work_id: W7330D967
    5abd9a7ae4a0483cbb8fb1e0b52b08cd:
      title: ༡༠༩  ཨ།
      base_file: ༡༠༩  ཨ།.txt
      work_id: W921A9BDF
    23bf47bd7b6348268e379fade713f3fe:
      title: ༡༡༠  ཀི།
      base_file: ༡༡༠  ཀི།.txt
      work_id: W24FA4AF4
    9229cf680141452f8891587f7b4b5634:
      title: ༡༡༡  ཁི།
      base_file: ༡༡༡  ཁི།.txt
      work_id: W2DD4FD79
    1fec69160b174550aacba284469776d6:
      title: ༡༡༢  གི
      base_file: ༡༡༢  གི.txt
      work_id: W7A3A6877
    6addc7abde20439aba7e09fa06279729:
      title: ༡༡༣  ངི་།
      base_file: ༡༡༣  ངི་།.txt
      work_id: W6A63A48A
    0c701affc73844bb977c1d4f89f264eb:
      title: ༡༡༤  ཅི།
      base_file: ༡༡༤  ཅི།.txt
      work_id: WCE36ED71
    3bb58c9a90704acfae85e6ecabe8749d:
      title: ༡༡༥  ཆི།
      base_file: ༡༡༥  ཆི།.txt
      work_id: W9C31F7ED
    ab7a3058764443888012719c074b34a8:
      title: ༡༡༦  ཇི།
      base_file: ༡༡༦  ཇི།.txt
      work_id: WDADF3EF0
    70de1a08267c4a418eaa2e1513d01625:
      title: ༡༡༧  ཉི།
      base_file: ༡༡༧  ཉི།.txt
      work_id: W3473BC8B
    bf205fc8c7644b32b10df0a385001b11:
      title: ༡༢༠  དི།
      base_file: ༡༢༠  དི།.txt
      work_id: W48479F24
    90ecd40ef2e04edb84084fb9ef1921f2:
      title: ༡༢༡  ནི།
      base_file: ༡༢༡  ནི།.txt
      work_id: WF7B93A2B
    13265266b47346b29ebe8c45e611c270:
      title: ༡༢༢  པི།
      base_file: ༡༢༢  པི།.txt
      work_id: W45D2AAD2
    6050a7786fd64d1b8a415e710ef81020:
      title: ༡༢༣  ཕི།
      base_file: ༡༢༣  ཕི།.txt
      work_id: WE67F3427
    8cd5d56734094e85aa928a2eb706c2ce:
      title: ༡༢༤  བི།
      base_file: ༡༢༤  བི།.txt
      work_id: WB488E518
    4abd87d39f8a4804b522f82f2e783746:
      title: ༡༢༧  ཚི།
      base_file: ༡༢༧  ཚི།.txt
      work_id: W0A6955A6
    97593c3d50344295b7527fe7e51d2a9a:
      title: ༡༢༨  ཛི།
      base_file: ༡༢༨  ཛི།.txt
      work_id: W2BD492C9
    c102d1ae0ad546008d26f38373e79c35:
      title: ༡༢༩  ཝི།
      base_file: ༡༢༩  ཝི།.txt
      work_id: W38E32377
    b4724a58f9cf4639b88b4dcbf07b82a3:
      title: ༡༣༡  ཟི།
      base_file: ༡༣༡  ཟི།.txt
      work_id: W74666718
    ca03e38729c34c33b5e3fa3c3d160616:
      title: ༡༣༢  འི།
      base_file: ༡༣༢  འི།.txt
      work_id: WCFC8DECF
    b164d581122f4a3387a68066794e854f:
      title: ༡༣༣  ཡི།
      base_file: ༡༣༣  ཡི།.txt
      work_id: W320E4386
    b7fc41a01b334ab6b91b8d6be86fb11f:
      title: ༡༣༤  རི།
      base_file: ༡༣༤  རི།.txt
      work_id: W277DD363
    a486caefb2d94e21a639a9260634fd21:
      title: ༡༣༥  ལི།
      base_file: ༡༣༥  ལི།.txt
      work_id: W20265779
    ab29b3abd39b41bcbf766b06db75bd6e:
      title: ༡༣༦  ཤི།
      base_file: ༡༣༦  ཤི།.txt
      work_id: W114414B0
    f9e6f42d125b4ed786adf9ad965e95bc:
      title: ༡༣༧  སི།
      base_file: ༡༣༧  སི།.txt
      work_id: W762E8234
    1d5e08cea3c84905855edfc9018a187e:
      title: ༡༣༨  ཧི།
      base_file: ༡༣༨  ཧི།.txt
      work_id: W3F2C94D9
    e3235e4b442b40888896e7a0308755b6:
      title: ༡༣༩  ཨི།
      base_file: ༡༣༩  ཨི།.txt
      work_id: W6FD11233
    f31b46f1d7b64ec88aa352748b61e6d4:
      title: ༡༤༠  ཀུ།
      base_file: ༡༤༠  ཀུ།.txt
      work_id: W84EFF3BF
    7ecabdbb0bb447d1a3600a51e96a5621:
      title: ༡༤༡  ཁུ།
      base_file: ༡༤༡  ཁུ།.txt
      work_id: W8A468602
    5a84951405c24f5c8e9118097516c2d4:
      title: ༡༤༧  ཉུ།
      base_file: ༡༤༧  ཉུ།.txt
      work_id: W6ABBF74E
    693ebc6451f149ecb7d952765c0c798b:
      title: ༡༤༨  ཏུ།
      base_file: ༡༤༨  ཏུ།.txt
      work_id: W81498B28
    c8df708441af4158aa67cd10fdad4d97:
      title: ༡༤༩  ཐུ།
      base_file: ༡༤༩  ཐུ།.txt
      work_id: W4B903353
    ea2432a750bf44fe9e72407d47c05cf3:
      title: ༡༥༡  ནུ།
      base_file: ༡༥༡  ནུ།.txt
      work_id: W487AD441
    d1afe9e582d84d4e817cf27bd44601c2:
      title: ༡༥༤  བུ།
      base_file: ༡༥༤  བུ།.txt
      work_id: W8B984689
    266459a9b12a467fa0f728f1030099e3:
      title: ༡༥༥  མུ།
      base_file: ༡༥༥  མུ།.txt
      work_id: W4C417455
    b0f725ee5e3146f28e7f739954b8af35:
      title: ༡༥༦  ཙུ།
      base_file: ༡༥༦  ཙུ།.txt
      work_id: W00EDBDAA
    bc3b6c166a7c47738a46a322a6cae09d:
      title: ༡༥༧  ཚུ།
      base_file: ༡༥༧  ཚུ།.txt
      work_id: WE4BB989D
    91d5d88faa434a679beb7358dacaf06d:
      title: ༡༥༨  ཛུ།
      base_file: ༡༥༨  ཛུ།.txt
      work_id: W13276214
    37a6fbe0c574429e8049ec3ed962b60c:
      title: ༡༥༩  ཝུ།
      base_file: ༡༥༩  ཝུ།.txt
      work_id: WF70F7F6C
    0c805ee5d1594708bfa7279e8d7c2045:
      title: ༡༦༤  རུ།
      base_file: ༡༦༤  རུ།.txt
      work_id: W748C9E28
    ac92ff9ca7ef47fd8e87b4f935b50b59:
      title: ༡༦༥  ལུ།
      base_file: ༡༦༥  ལུ།.txt
      work_id: WE3331E33
    63437d4b515a4e08be16c498150f2054:
      title: ༡༦༦  ཤུ།
      base_file: ༡༦༦  ཤུ།.txt
      work_id: WC2F12524
    759c3f3a04294b29b73bded60fae8ca6:
      title: ༡༦༧  སུ།
      base_file: ༡༦༧  སུ།.txt
      work_id: W8A3776B6
    90e99027adb24e888f86f4810e14add5:
      title: ༡༦༨  ཧུ།
      base_file: ༡༦༨  ཧུ།.txt
      work_id: W96A6465F
    b5107d4dd22a4f7a82e7409059e63eee:
      title: ༡༦༩  ཨུ།
      base_file: ༡༦༩  ཨུ།.txt
      work_id: W454BE728
    7313913e89e34576b7c37dadc1de2a60:
      title: ༡༧༢  གེ
      base_file: ༡༧༢  གེ.txt
      work_id: W77464E87
    e9b4c51f14254f27a7c69b338e41e31b:
      title: ༡༧༢  གེ
      base_file: ༡༧༢  གེ.txt
      work_id: W77464E87
    68d81c5bb97d4af2aef99bac4bd6c3f4:
      title: ༡༧༣  ངེ་།
      base_file: ༡༧༣  ངེ་།.txt
      work_id: W1A250931
    242ef1739bae4515833c6b8e2b7f015a:
      title: ༡༧༤  ཅེ།
      base_file: ༡༧༤  ཅེ།.txt
      work_id: WF32E248D
    766daa24e50b45bdbe4a294c49df1e3f:
      title: ༡༧༥  ཆེ།
      base_file: ༡༧༥  ཆེ།.txt
      work_id: W4D2277D8
    b368d5dba7724d839b16e46a1c6f09a4:
      title: ༡༨༢  པེ།
      base_file: ༡༨༢  པེ།.txt
      work_id: W1DAEA60A
    02fb90d12d754d1586a91b2fad9942f7:
      title: ༡༨༣  ཕེ།
      base_file: ༡༨༣  ཕེ།.txt
      work_id: W478361FF
    0871aaef20424fe38a9d178838956107:
      title: ༡༨༧  ཚེ།
      base_file: ༡༨༧  ཚེ།.txt
      work_id: W73452452
    d59dd6a9adab456d84953e3243c30438:
      title: ༡༨༨  ཛེ།
      base_file: ༡༨༨  ཛེ།.txt
      work_id: W7548DE34
    0307d336015c40d0b1ed8378cbba0305:
      title: ༡༨༩  ཝེ།
      base_file: ༡༨༩  ཝེ།.txt
      work_id: W0009DE0D
    8347ec4ceb93433a858163222f9b48a3:
      title: ༡༩༠  ཞེ།
      base_file: ༡༩༠  ཞེ།.txt
      work_id: WAE3FF24E
    6960726283b94af8ad2ac5720b273a14:
      title: ༡༩༡  ཟེ།
      base_file: ༡༩༡  ཟེ།.txt
      work_id: W09832F38
    2d33124c717a42c3b3b4742282f73749:
      title: ༡༩༣  ཡེ།
      base_file: ༡༩༣  ཡེ།.txt
      work_id: WCF85388A
    d875fd04c4814945ba7ecedca8cd5332:
      title: ༡༩༤  རེ།
      base_file: ༡༩༤  རེ།.txt
      work_id: W4BFBD719
    06385cb7ce8b4f00a332dc13b373d004:
      title: ༡༩༥  ལེ།
      base_file: ༡༩༥  ལེ།.txt
      work_id: W4247E3A4
    03f4390715324c5997dc810c7927fbc7:
      title: ༡༩༦  ཤེ།
      base_file: ༡༩༦  ཤེ།.txt
      work_id: WFD142DC5
    f35bccec5bd547089a5ead7e3ea187d8:
      title: ༡༩༧  སེ།
      base_file: ༡༩༧  སེ།.txt
      work_id: W3A8A3954
    59d9d657feea4bd2b9ffcb4e12d47e45:
      title: ༡༩༨  ཧེ།
      base_file: ༡༩༨  ཧེ།.txt
      work_id: W956FD2D9
    00f7b736bbb44d3482760015cd623a89:
      title: ༢༠༣  ངོ་།
      base_file: ༢༠༣  ངོ་།.txt
      work_id: WC26EEE62
    73fdb0684c104a098acfc7b048cac7f1:
      title: ༢༠༣  ངོ་།
      base_file: ༢༠༣  ངོ་།.txt
      work_id: WC26EEE62
    980016ae3a884873a103ff5ba8bfc701:
      title: ༢༠༤  ཅོ།
      base_file: ༢༠༤  ཅོ།.txt
      work_id: WBC2B2092
    ef132d1bd3d14a8aa125221c8ecab896:
      title: ༢༠༦  ཇོ།
      base_file: ༢༠༦  ཇོ།.txt
      work_id: W890E4B58
    cd59ea0da91c4266968c10b658fcc620:
      title: ༢༠༧  ཉོ།
      base_file: ༢༠༧  ཉོ།.txt
      work_id: WBE02008A
    a0d2b791ab17472f83bc860c170aac29:
      title: ༢༡༡  ནོ།
      base_file: ༢༡༡  ནོ།.txt
      work_id: W3334D174
    eb312a9615ab411c80419b7762aa6b34:
      title: ༢༡༢  པོ།
      base_file: ༢༡༢  པོ།.txt
      work_id: WA9E21FE4
  work_id_vol:
    WE43E33FB: ༠༡  བསྟོད་ཚོགས།
    W1EB08EBF: ༠༢  རྒྱུད།
    W9B9B1099: ༠༣  ཤེས་ཕྱིན།
    W8E855124: ༠༤  དབུ་མ།
    W2C57486D: ༠༥  མདོ་གྲེལ།
    WE8439027: ༠༦  སེམས་ཙམ།
    W606C3A83: ༠༧  མངོན་པ།
    W22D26250: ༠༨  འདུལ་བ།
    W9290FE69: ༠༩  སྐྱེས་རབས།
    WE4F89738: ༡༠  སྤྲིང་ཡིག
    W344E4EB4: ༡༡  ཚད་མ།
    W4FBF8F48: ༡༢  སྒྲ་མདོ།
    WD9A1D3DA: ༡༣  གསོ་བ་རིག་པ།
    WA9C9FEE6: ༡༤  བཟོ་རིག
    W3FF676E5: ༡༥  ལུགས་ཀྱི་བསྟན་བཅོས།
    W189687F9: ༡༦  སྣ་ཚོགས།
created_at: '2022-04-04T12:32:06.982364'
last_modified_at: '2022-04-04T12:32:06.982372'
